# Regression Discontinuity Design (RDD)

- https://github.com/CausalAIBook/MetricsMLNotebooks/blob/main/T/T_4_Regression_Discontinuity_on_Progresa_Data.ipynb
- 근데 ipynb에서 이슈가 있다고 생각되어 https://github.com/CausalAIBook/MetricsMLNotebooks/issues/37 와 같이 이슈를 남겨두었습니다.
- https://matheusfacure.github.io/python-causality-handbook/16-Regression-Discontinuity-Design.html 을 이용한 코드를 사용해도 되지만 단순한 시각화 코드가 아니라 RDD, RDROBUST 함수 등을 이용해서 통계적인 검정을 할 수 있는 코드로 변경하면 좋겠습니다.

In [2]:
import pandas as pd

df = pd.read_csv("../data/causal_ml_data/progresa.csv",index_col=0)
df = df.dropna()

df.rename(columns={"index": "pov_index"}, inplace=True)

print(df.columns)
df.head()

Index(['hhpiso', 'hhrooms', 'hhwater', 'hhwaterin', 'hhbano', 'hhownhouse',
       'hhsize', 'hhelect', 'clus', 'headmale', 'headage', 'heademp',
       'wifeage', 'wifeeduc', 'headeduc', 'child_0to5', 'boy_0to5',
       'pov_index', 'conspcfood_t0', 'conspcfood_t1', 'conspcfood_t2',
       'conspcnonfood_t0', 'conspcnonfood_t1', 'conspcnonfood_t2', 'conspc_t0',
       'conspc_t1', 'conspc_t2'],
      dtype='object')

,hhpiso,hhrooms,hhwater,hhwaterin,hhbano,hhownhouse,hhsize,hhelect,clus,headmale,...,pov_index,conspcfood_t0,conspcfood_t1,conspcfood_t2,conspcnonfood_t0,conspcnonfood_t1,conspcnonfood_t2,conspc_t0,conspc_t1,conspc_t2
1,1.0,1.0,1.0,1.0,1.0,0.0,5,1,1,1,...,1.5410,260.223999,374.071991,379.208008,106.186668,183.149323,57.127998,366.410675,557.221313,436.335999
2,1.0,1.0,1.0,0.0,0.0,1.0,5,1,1,1,...,-0.6615,265.359985,574.375977,195.167999,87.266663,160.013336,112.136002,352.626648,734.389282,307.304016
3,1.0,1.0,0.0,0.0,1.0,1.0,4,1,1,1,...,-0.3240,604.549988,433.350006,367.010010,348.813324,263.083344,123.323334,953.363281,696.433350,490.333344
4,0.0,1.0,0.0,0.0,1.0,0.0,6,1,1,1,...,1.1500,233.259995,281.766663,260.468567,100.877777,140.233337,36.325714,334.137756,422.000000,296.794281
6,1.0,1.0,1.0,0.0,1.0,1.0,4,1,1,1,...,-0.8260,280.339996,185.110001,364.869995,158.416656,201.183334,68.000000,438.756653,386.293335,432.869995

## Sharp RDD

## Fuzzy RDD ( = IV)

## 질문이나 의견을 남겨주세요.
<script src="https://utteranc.es/client.js"
        repo="myeongseok-gwon/teachbook-test"
        issue-term="pathname"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script>